# Generated by Django 2.2.12 on 2020-05-29 11:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('photo', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='recette',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='uploads/% Y/% m/% d/'),
        ),
        migrations.AddField(
            model_name='recette',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='uploads/% Y/% m/% d/'),
        ),
        migrations.AddField(
            model_name='recette',
            name='photo_principale',
            field=models.ImageField(default='', upload_to='uploads/% Y/% m/% d/'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='recette',
            name='ingredients',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='recette',
            name='photo',
            field=models.ImageField(blank=True, upload_to='uploads/% Y/% m/% d/'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='preparation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recette',
            name='categorie',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Categorie'),
        ),
    ]
